version: '3'

services:
  postgres:
    # build the container and set the name
    build:
      context: .
      dockerfile: dockerfile.postgres

    container_name: postgres

    # expose the postgres port
    ports:
      - 5432:5432

    # p[rovide password based on environment variable]
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data

  php:
    build:
      context: .
      dockerfile: dockerfile.php

    container_name: php

    # open port 80 as 8080
    ports:
      - 8080:80

    # link it to postgres
    links:
      - postgres

    # make the /var/www/html volume available as ./app and initalize
    # the 000-default.conf file
    volumes:
      - ${APP_DIR}:/var/www/html
      - ./init.php/vhost.conf:/etc/apache2/sites-enabled/000-default.conf

  flyspray:
    build:
      context: .
      dockerfile: dockerfile.flyspray

    container_name: flyspray

    # link it to php-apache
    links:
      - php

    # make the /var/www/html volume available as ./app
    volumes:
      - ${APP_DIR}:/app
